# coding: utf-8

"""
    CERN Unified Storage API

    A unified storage API for all data-storage back-ends.

    OpenAPI spec version: 3.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "sapi"
VERSION = "0.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
        "urllib3 >= 1.15", 
        "six >= 1.10", 
        "certifi", 
        "python-dateutil", 
        "fire", 
        "requests",
        "requests_kerberos"
        ]

setup(
    name=NAME,
    version=VERSION,
    description="CERN Unified Storage API client",
    author_email="",
    url="",
    keywords=["Swagger", "CERN Unified Storage API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    scripts=["bin/sapi"],
    include_package_data=True,
    long_description="""\
    Client for the CERN IT-DB Storage API"
    """,
)
